apiVersion: v1
kind: Service
metadata:
  name: app
  labels:
    app.kubernetes.io/component: app
spec:
  selector:
    app.kubernetes.io/component: app
  ports:
    - name: client
      port: 80
      targetPort: client
    - name: server
      port: 3000
      targetPort: server
