apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app.kubernetes.io/component: app
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: app
  template:
    metadata:
      labels:
        app.kubernetes.io/component: app
    spec:
      containers:
        - name: client
          image: ghcr.io/digitalinteraction/datadiaries-client
          resources:
            requests: { memory: 32Mi, cpu: 50m }
            limits: { memory: 128Mi, cpu: 100m }
          ports:
            - name: client
              containerPort: 80
          volumeMounts:
            - mountPath: /usr/share/nginx/html/config.js
              name: resources
              subPath: config.js
              readOnly: true
            - mountPath: /etc/nginx/conf.d/default.conf
              name: resources
              subPath: nginx.conf
              readOnly: true
          readinessProbe:
            tcpSocket: { port: 80 }
            initialDelaySeconds: 1
          livenessProbe:
            httpGet: { path: /healthz, port: 80 }
            initialDelaySeconds: 5

        - name: server
          image: ghcr.io/digitalinteraction/datadiaries-server
          resources:
            requests: { memory: 64Mi, cpu: 500m }
            limits: { memory: 256Mi, cpu: 600m }
          ports:
            - name: server
              containerPort: 3000
          envFrom:
            - secretRef: { name: app-env }
          volumeMounts:
            - mountPath: /app/app-config.json
              name: resources
              subPath: app-config.json
              readOnly: true
          readinessProbe:
            tcpSocket: { port: 3000 }
            initialDelaySeconds: 5
          livenessProbe:
            httpGet: { path: /healthz, port: 3000 }
            initialDelaySeconds: 5
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000

      volumes:
        - name: resources
          configMap:
            name: resources

      securityContext:
        fsGroup: 1000
