apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# namespace: ...
namePrefix: data-officer-
commonLabels:
  app.kubernetes.io/name: data-officer

resources:
  - app-deployment.yml
  - app-service.yml
  - app-ingress.yml
  - redis-pvc.yml
  - redis-deployment.yml
  - redis-service.yml
  - repos-pvc.yml
  - repos-cronjob.yml
  - coffee-am-cronjob.yml
  - coffee-pm-cronjob.yml
  - commits-cronjob.yml

secretGenerator:
  - name: app-env
    env: secret/data-officer.env
  - name: bot-ssh
    files:
      - secret/bot_id
      - secret/bot_id.pub
  - name: auth
    files:
      - secret/auth.yml

configMapGenerator:
  - name: app-resources
    files:
      - config/known_hosts

images:
  - name: ghcr.io/digitalinteraction/data-officer
    newTag: 1.0.0
  - name: redis
    newTag: 7-alpine
